### ISSUE TITLE
wks controller crashing (after build during drain.go)

### ISSUE THREAD

**Issue by taemon1337** [weaveworks/wksctl#309]
```
ime="2020-10-06T11:22:44Z" level=warning msg="ignoring DaemonSet-managed Pods: kube-system/kube-proxy-vlnc6, kube-system/weave-net-sbjrm"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4dfd77]
 
goroutine 1457 [running]:
fmt.Fprintf(0x0, 0x0, 0x18b0382, 0x13, 0xc000852b20, 0x2, 0x2, 0xb7366a6d27fec294, 0x7222acfad3825444, 0xd80043947d4aa0f)
	/usr/local/go/src/fmt/print.go:205 +0x77
k8s.io/kubectl/pkg/drain.(*Helper).evictPods.func1(0xc0000869a0, 0x1bac940, 0xc000e0a000, 0xc000e02368, 0xc000c17e00, 0xe, 0xc000936180, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/k8s.io/kubectl@v0.18.5/pkg/drain/drain.go:262 +0x926
created by k8s.io/kubectl/pkg/drain.(*Helper).evictPods
	/go/pkg/mod/k8s.io/kubectl@v0.18.5/pkg/drain/drain.go:256 +0x22f
```

wkctl cluster build using kubernetes version: v1.17.4

**Comment by taemon1337** [comment]
Maybe related to https://github.com/weaveworks/wksctl/pull/251

**Comment by taemon1337** [comment]
The cluster did get installed correctly and nodes got to ready state with a single master node cordoned.

**Comment by taemon1337** [comment]
UPDATE: after I restarted the cluster nodes the wks controller stopped crashing and the cluster looks good, looks like a bug that may not really do any damage in this case but i'll leave someone else to determine its validity.
